site_name: Guia de Monitoramento Estratégico
site_description: Guia de Monitoramento Estratégico da CGE-MG

theme:
  name: material
  language: pt-BR

  palette:
    primary: blue
    accent: light blue

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/external-links.js

nav:
  - Início: index.md

  - Bases de Dados:
      - Visão Geral: bases-dados/index.md
      - Estrutura da Unidade: bases-dados/estrutura-rh.md
      - PACI: bases-dados/paci.md
      - RACI: bases-dados/raci.md
      - Manifestações: bases-dados/manifestacoes.md
      - e-CGU: bases-dados/e-cgu.md

  - Monitoramento Estratégico:
      - Metodologia: monitoramento/metodologia.md
      - Estrutura da Unidade: monitoramento/estrutura-rh.md
      - PACI: monitoramento/paci.md
      - RACI: monitoramento/raci.md
      - Manifestações: monitoramento/manifestacoes.md
      - E-CGU: monitoramento/sistema-e-cgu.md
      - Utilização Integrada das Bases de Dados: monitoramento/analises-integradas.md 
