site_name: Guia de Monitoramento Estratégico
site_description: Guia de Monitoramento Estratégico da CGE-MG

theme:
  name: material
  language: pt-BR

  palette:
    primary: green
    accent: light green

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md

  - 1. Monitoramento:
      - PACI: monitoramento/paci.md
      - PO: monitoramento/po.md

  - 2. Sistema de Auditoria – e-CGU:
      - Manual prático: ecgu/manual.md

  - 3. Referências e Apoio:
      - Normativos: referencias/normativos.md
      - Canais de apoio: referencias/apoio.md

  
